version: "3.8"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge

services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    restart: always
    command:
      - "--api=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file=true"
      - "--providers.file.directory=/config"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.middlewares=secureHeaders@file"
      - "--entrypoints.websecure.http.middlewares=compressFiles@file"
      - "--entrypoints.websecure.http.tls.options=default"
      - "--entrypoints.websecure.http.tls.certresolver=default"
      - "--certificatesresolvers.default.acme.dnschallenge=true"
      - "--certificatesresolvers.default.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.default.acme.email=$ACME_EMAIL"
      - "--certificatesresolvers.default.acme.storage=/letsencrypt/acme.json"
      - "--pilot.token=$PILOT_TOKEN"
    labels:
      - "traefik.http.routers.dashboard.rule=Host(`$DOMAIN_NAME`)"
      - "traefik.http.routers.dashboard.service=api@internal"
    networks:
      - traefik_proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
          - "CF_DNS_API_TOKEN=$CF_DNS_API_TOKEN"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./config:/config"
      - "./letsencrypt:/letsencrypt"
  
